---
- include: fedora.yml
  when: is_rhel7.rc != 0 and is_centos7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- name: Write etcd global config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify:
        - restart etcd

- name: Enable etcd
  service: name=etcd enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0
