---
- include: fedora.yml
  when: is_rhel7.rc != 0 and is_centos7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- name: write the global config file
  template: src=config.j2 dest=/etc/kubernetes/config
  notify:
          - restart daemons
